import LenisProvider from "@/providers/useLenis";
import "./globals.css";

export const metadata = {
  title: "Utkarsh Verma's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
